version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_root_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_root_password
    secrets:
      - minio_root_user
      - minio_root_password
    command: server /data --console-address ":9001"

volumes:
  minio_data:

secrets:
  minio_root_user:
    file: ./minio_root_user.txt
  minio_root_password:
    file: ./minio_root_password.txt
